// Code generated by "stringer -type ErrorCode --linecomment"; DO NOT EDIT.

package errorcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[FILE_NOT_FOUND-1001]
	_ = x[FILE_MOD_ERROR-1002]
	_ = x[FILE_TOO_BIG-1003]
}

const (
	_ErrorCode_name_0 = "OK"
	_ErrorCode_name_1 = "file not foundfile mode errorfile too big"
)

var (
	_ErrorCode_index_1 = [...]uint8{0, 14, 29, 41}
)

func (i ErrorCode) String() string {
	switch {
	case i == 0:
		return _ErrorCode_name_0
	case 1001 <= i && i <= 1003:
		i -= 1001
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
